# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a3d1d7b9eba54adf32879146e18bb5e01ebce48ece88ee9adb789947532174f90dd130ccfc07b577e0076bf00192d7726967cc80b6bc7c0466c01698b09b6b5

test:
  secret_key_base: f4e5a4c2ecad8702a615faa7e6de23017f4c6eb5e355efaefba46f56e48448eb7e7cacd40f472dd36914d0bd684712f7804389bb8882eeee89e9228dba45ead2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
